### ISSUE TITLE
Write Delivery Documentation

### ISSUE THREAD

**Issue by mehalter** [ideas-team/IDEAS-Conference-Planner#42]
Check out the `documentation` branch and fill in the `README.md` and `RELEASE-NOTES.md` files with a complete list of features/functionality, and how to set up, install, and run our software from nothing.

For the install notes, list requirements like npm/nodejs and a postgresql installation, and then clearly document how to install dependencies, set up the config file from the template, running the program, how to ingest the CSV file, etc.

**Comment by kraemerk** [comment]
Done
